.before-script-build: &before-script-build
  - |
    if [[ ! -z "$CI_BUILDX_PLATFORMS" ]]; then
      export OS_ARCH=`echo $CI_BUILDX_PLATFORMS | tr ',' '\n' | \
      sed 's|\/||2' | sed 's|\/|-|' | tr '\n' ' '`
    fi
  - |
    export CI_APP_REPO=${CI_APP_REPO:-$CI_REGISTRY_IMAGE}
    if [[ $CI_COMMIT_BRANCH == "master" ]]; then
      export CI_APP_TAG=${CI_APP_TAG:-latest}
    elif [[ $CI_COMMIT_BRANCH == "freeze-version" ]]; then
      export CI_APP_TAG=${CI_APP_TAG:-1.5.2}
    else
      export CI_APP_TAG=${CI_APP_TAG:-$CI_COMMIT_SHA}
    fi
  - >
    echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER
    --password-stdin $CI_REGISTRY
  - |
    export VERSION_MAJ_MIN_PAT=`sed -n \
    "s|.*JULIA_VERSION:-\([0-9]\.[0-9]\.[0-9]\).*|\1|p" ver/latest.Dockerfile`
    export VERSION_MAJ_MIN=`echo "${VERSION_MAJ_MIN_PAT:0:3}"`
    export VERSION_MAJ=`echo "${VERSION_MAJ_MIN_PAT:0:1}"`

.build:
  image: registry.gitlab.b-data.ch/docker/docker-buildx:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - *before-script-build

buildx:latest-linux-amd64:
  extends: .build
  tags:
    - os:linux
  script:
    - docker context create tls-environment
    - docker buildx create --name multiarch-builder --use tls-environment
    - >
      docker buildx build --pull --push
      --platform linux/amd64
      -t $CI_APP_REPO:$CI_APP_TAG-linux-amd64
      -t $CI_APP_REPO:$VERSION_MAJ_MIN_PAT-linux-amd64
      -t $CI_APP_REPO:$VERSION_MAJ_MIN-linux-amd64
      -t $CI_APP_REPO:$VERSION_MAJ-linux-amd64
      -f ver/$CI_APP_TAG.Dockerfile .
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_BUILDX_PLATFORMS =~ /(linux\/amd64)/
      changes:
        - ver/latest.Dockerfile

buildx:latest-linux-arm64v8:
  extends: .build
  tags:
    - os:linux
  script:
    - docker context create tls-environment
    - docker buildx create --name multiarch-builder --use tls-environment
    - >
      docker buildx build --pull --push
      --platform linux/arm64/v8
      -t $CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
      -t $CI_APP_REPO:$VERSION_MAJ_MIN_PAT-linux-arm64v8
      -t $CI_APP_REPO:$VERSION_MAJ_MIN-linux-arm64v8
      -t $CI_APP_REPO:$VERSION_MAJ-linux-arm64v8
      -f ver/$CI_APP_TAG.Dockerfile .
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_BUILDX_PLATFORMS =~ /(linux\/arm64\/v8)/
      changes:
        - ver/latest.Dockerfile

buildx:version-linux-amd64:
  extends: .build
  tags:
    - os:linux
  script:
    - docker context create tls-environment
    - docker buildx create --name multiarch-builder --use tls-environment
    - >
      docker buildx build --pull --push
      --platform linux/amd64
      -t $CI_APP_REPO:$CI_APP_TAG-linux-amd64
      -f ver/$CI_APP_TAG.Dockerfile .
  rules:
    - if: $CI_COMMIT_BRANCH == "freeze-version" && $CI_BUILDX_PLATFORMS =~ /(linux\/amd64)/
      changes:
        - ver/1.5.2.Dockerfile

buildx:version-linux-arm64v8:
  extends: .build
  tags:
    - os:linux
  script:
    - docker context create tls-environment
    - docker buildx create --name multiarch-builder --use tls-environment
    - >
      docker buildx build --pull --push
      --platform linux/arm64/v8
      -t $CI_APP_REPO:$CI_APP_TAG-linux-arm64v8
      -f ver/$CI_APP_TAG.Dockerfile .
  rules:
    - if: $CI_COMMIT_BRANCH == "freeze-version" && $CI_BUILDX_PLATFORMS =~ /(linux\/arm64\/v8)/
      changes:
        - ver/1.5.2.Dockerfile

build-manifest:latest-linux-multiarch:
  extends: .build
  stage: deploy
  script:
    - |
      for i in $OS_ARCH; do
        export CI_MANIFEST_LIST="$CI_MANIFEST_LIST $CI_APP_REPO:$CI_APP_TAG-$i"
      done
    - >    
      docker manifest create $CI_APP_REPO:$CI_APP_TAG $CI_MANIFEST_LIST
      && docker manifest push $CI_APP_REPO:$CI_APP_TAG

      docker manifest create $CI_APP_REPO:$VERSION_MAJ_MIN_PAT $CI_MANIFEST_LIST
      && docker manifest push $CI_APP_REPO:$VERSION_MAJ_MIN_PAT

      docker manifest create $CI_APP_REPO:$VERSION_MAJ_MIN $CI_MANIFEST_LIST
      && docker manifest push $CI_APP_REPO:$VERSION_MAJ_MIN

      docker manifest create $CI_APP_REPO:$VERSION_MAJ $CI_MANIFEST_LIST
      && docker manifest push $CI_APP_REPO:$VERSION_MAJ
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - ver/latest.Dockerfile

build-manifest:version-linux-multiarch:
  extends: .build
  stage: deploy
  script:
    - |
      for i in $OS_ARCH; do
        export CI_MANIFEST_LIST="$CI_MANIFEST_LIST $CI_APP_REPO:$CI_APP_TAG-$i"
      done
    - >    
      docker manifest create $CI_APP_REPO:$CI_APP_TAG $CI_MANIFEST_LIST
      && docker manifest push $CI_APP_REPO:$CI_APP_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "freeze-version"
      changes:
        - ver/1.5.2.Dockerfile
