image: docker:stable
services:
  - docker:stable-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - export VERSION_MAJ_MIN_PAT=`sed -n "s|.*JULIA_VERSION:-\([0-9]\.[0-9]\.[0-9]\).*|\1|p" ver/latest.Dockerfile`
  - export VERSION_MAJ_MIN=`echo "${VERSION_MAJ_MIN_PAT:0:3}"`

build-latest:
  stage: build
  script:
    - cd ver && docker build --pull -t $CI_REGISTRY_IMAGE:latest -f latest.Dockerfile .
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$VERSION_MAJ_MIN_PAT
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$VERSION_MAJ_MIN
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$VERSION_MAJ
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$VERSION_MAJ_MIN_PAT
    - docker push $CI_REGISTRY_IMAGE:$VERSION_MAJ_MIN
    - docker push $CI_REGISTRY_IMAGE:$VERSION_MAJ
  only:
    refs:
      - master
    changes:
      - ver/latest.Dockerfile

build-version:
  stage: build
  script:
    - cd ver && docker build --pull -t $CI_REGISTRY_IMAGE:1.3.1 -f 1.3.1.Dockerfile .
    - docker tag $CI_REGISTRY_IMAGE:1.3.1 $CI_REGISTRY_IMAGE:1.3
    - docker push $CI_REGISTRY_IMAGE:1.3.1
    - docker push $CI_REGISTRY_IMAGE:1.3
  only:
    refs:
      - freeze-version
    changes:
      - ver/1.3.1.Dockerfile
